[package]
name = "cryptography"
version = "0.1.0"
authors = [ "Jesse Lancaster <jesse@polymath.network>",
            "Parnian Alimi   <parnian@polymath.network>",
          ]
readme = "README.md"
repository = "https://github.com/PolymathNetwork/cryptography"
description = "The Repository for cryptographic libraries used in Polymesh"
edition = "2018"
exclude = [".gitignore"]
build = "build.rs"

[dependencies]
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false, rev = "93569d0d1af7aa5eb67b9de8b58d7fffde63b421" }

curve25519-dalek = { version = "2.0.0", default-features = false }
bulletproofs = { version = "2.0", default-features = false }
sha3 = { version = "0.8", default-features = false }
rand = { version = "0.7.3", default-features = false, optional = true }
rand_core = { version = "0.5.1", default-features = false }
getrandom = { version = "0.1.14", default-features = false, optional = true }
serde = { version = "1.0.104", default-features = false, optional = true }
schnorrkel = { version = "0.9.0", features = ["u64_backend"], default-features = false, optional = true }


[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", git = "https://github.com/paritytech/substrate", default-features = false, rev = "93569d0d1af7aa5eb67b9de8b58d7fffde63b421"}


[dev-dependencies]
rand = "0.7.3"

[features]
default = ["std", "rand", "getrandom"]
no_std = []
nightly = ["curve25519-dalek/nightly", ]
std = [
	"rand", 
	"rand/std", 
	"schnorrkel/std", 
	"sp-std/std",
]

[[example]]
# Use `cargo +nightly build --example simple` to compile this example.
name = "simple"
path = "src/examples/simple.rs"

