[package]
name = "cryptography"
version = "0.1.0"
authors = [ "Jesse Lancaster <jesse@polymath.network>",
            "Parnian Alimi   <parnian@polymath.network>",
            "Arash Afshar    <arash@polymath.network>",
          ]
readme = "README.md"
repository = "https://github.com/PolymathNetwork/cryptography"
description = "The Repository for cryptographic libraries used in Polymesh"
edition = "2018"
exclude = [".gitignore"]

[dependencies]
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false, rev = "93569d0d1af7aa5eb67b9de8b58d7fffde63b421" }

# Common
serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_bytes = { version = "0.11", default-features = false, features = ["alloc"] }
byteorder = { version = "1.3.4", default-features = false }
failure = "0.1.7"
zeroize = { version = "1.1", default-features = false }

# Crypto
curve25519-dalek = { version = "2", default-features = false }
merlin = { version = "2.0.0", default-features = false }
schnorrkel = { version = "0.9.1", default-features = false }

getrandom = { version = "0.1.14", default-features = false, optional = true } 
rand_core = { version = "0.5", default-features = false }
sha3 = { version = "0.8", default-features = false }

# Customized libraries for no_std.
bulletproofs = { git = "https://github.com/fmiguelgarcia/bulletproofs.git", branch = "CRYP-92/integration_test", default-features = false }

[build-dependencies]
# WASM builder is using `WasmBuilderSource::Crates("1.0.8")`, please see `build.rs`.
wasm-builder-runner = { package = "substrate-wasm-builder-runner", git = "https://github.com/paritytech/substrate", default-features = false, rev = "93569d0d1af7aa5eb67b9de8b58d7fffde63b421" }

[dev-dependencies]
wasm-bindgen-test = "0.3.10"
criterion = "0.3"
env_logger = "0.7.1"


[features]
common = [
	"curve25519-dalek/nightly", 
	"curve25519-dalek/serde", 
	"curve25519-dalek/alloc",
]
u64_backend = [
	"curve25519-dalek/u64_backend",
	"schnorrkel/u64_backend"
]
avx2_backend = [
	"curve25519-dalek/avx2_backend",
	"schnorrkel/avx2_backend"
]
u32_backend = [
	"curve25519-dalek/u32_backend", 
	"schnorrkel/u32_backend"
]

default = ["std"]
no_std = [
	"getrandom/wasm-bindgen",
	"rand_core/alloc",
	"rand_core/getrandom",
	"common", 
	"u32_backend",
	"bulletproofs/no_std",
	"schnorrkel/wasm-bindgen"
]
std = [ 
	"sp-std/std", 
	"rand_core/std",
	"common", 
	"avx2_backend",
	"bulletproofs/std",
	"schnorrkel/std"
]

[[bench]]
name = "elgamal_decryption"
harness = false
